### ISSUE TITLE
支持通过环境变量配置node的cpu/mem/disk

### ISSUE THREAD

**Issue by jessehu** [smartxworks/cluster-api-provider-elf#13]
CAPE中 cpu/mem/disk的值 在cluster-template.yaml中没有模板变量. 需要添加相应支持. 比如CAPV中支持这么设置:
export VSPHERE_WORKER_DISK_GIB=“40”
export VSPHERE_WORKER_MEM_MIB=“8192"
export VSPHERE_WORKER_NUM_CPUS=“4”

**Comment by haijianyang** [comment]
这些参数好像是 TKG 支持的，不是 CAPE 模板提供的？

**Comment by jessehu** [comment]
fixed in https://github.com/smartxworks/cluster-api-provider-elf/pull/19
