### ISSUE TITLE
CAPE 同时创建两个不同CloudTower上的k8s集群时失败

### ISSUE THREAD

**Issue by jessehu** [smartxworks/cluster-api-provider-elf#25]
1. 先使用CAPE在CloudTower Server A的ELF Cluster 1上创建K8s集群. 创建成功.
2. 再使用CAPE在CloudTower Server B的ELF Cluster 2上创建K8s集群. 创建失败. CAPE log显示错误:

> elfmachine_controller.go:442] cape-controller-manager/elfmachine-controller “msg”=“failed to create VM” “error”=“CLUSTER_NOT_FOUND” “elfCluster”=“huhui-local-kscluster” “elfMachine”=“huhui-local-kscluster-control-plane-b5nt4" “namespace”=“default” “taskRef”=“” “vmRef”=“”

@haijianyang 发现是这里没有处理同时连接两个Tower的情况:
![图片](https://user-images.githubusercontent.com/10006/169449299-08d055a7-8d27-4749-8f8a-462532f32b17.png)

**Comment by haijianyang** [comment]
[关联](https://github.com/smartxworks/cluster-api-provider-elf/issues/25)
