### ISSUE TITLE
BUG: 已经处于删除状态的集群在重启cape控制器之后不应该Power On已关闭的vm

### ISSUE THREAD

**Issue by klzsysy** [smartxworks/cluster-api-provider-elf#34]
## 过程
1. delete cluster
2. 进行到一半（删除了部分vm）的时候停止cape controller
3. 手动将集群剩余vm全部关机
4. 启动controller
5. controller继续删掉未完成的vm，**但同时将还未进入删除状态vm进行了开机**，然后再依次关机删除

## 预期
处于delete状态的集群，不应该再poweron vm

**Comment by klzsysy** [comment]
简单的说：在销毁集群的过程中，删除过程是先PowerOff 再删除vm，因此不应该再有PowerOn vm的操作

**Comment by haijianyang** [comment]
参照 CAPI 的设计文档，以及 CAPV、CAPA 等的实现，未标记为删除的 Machine（虽然 Cluster 已经被标记为删除），会继续正常 reconcile，所以继续启动关闭的虚拟机应该是合理的。

**Comment by jessehu** [comment]
ok
